### ISSUE TITLE
Parser does not add as many translations as it says it did

### ISSUE THREAD

**Issue by Heldenkrieger01** [i18next/i18next-parser#498] opened 2021-12-28 19:05 UTC
## 🐛 Bug Report

When running the parser in debug mode, it tells you, how many unique keys it has found and how many new keys it added.
In my project, the parser says it has added 249 keys, but in reality only 227 get written to the output file. This is frustrating, since it seems to pick the translation up, but not actually writing them...

## To Reproduce

Multiple files are affected, they contain translation keys like all other files.
I cannot see a pattern.

## Expected behavior

All keys are actually added to the output file.

## Your Environment

- *runtime version*: node v16.10
- *i18next version*: 21.6.4
 - *i18next-parser version*:  5.2.0
- *os*: Windows

**Comment by karellm** [comment] 2022-03-13 03:59
@Heldenkrieger01 Can you provide me with a reproduceable example?

**Comment by alk-mandrianarijaona** [comment] 2022-03-23 14:43
So as a workaround, I currently use a pinned commit version of i18next-parser by setting `"i18next-parser": "https://github.com/i18next/i18next-parser.git#d863cd188a0ae1da68ad455fe39ba33f7db75bc6",` in my `package.json`.

**Comment by karellm** [comment] 2022-03-28 02:36
Could you provide me with a reproducible project? This seems to be a severe bug and I will happily tackle it

**Comment by alk-mandrianarijaona** [comment] 2022-03-29 08:48
@karellm I will try to create a reproduction project. Our project is a private app with 3k+ files and on a small CRA project, I could not reproduce it with the small amount of code there.

**Comment by Laityned** [comment] 2022-04-03 12:14
Possible related to the same origin of the bug as described in issue #489.

In that case PR #546 would fix this issue.

**Comment by karellm** [comment] 2022-04-03 16:52
This is fixed in `6.2.0`. Please not that `unique count` now includes plurals since it makes more sense with the new plural form.

**Closed by karellm** 2022-04-03 16:52 UTC
