### ISSUE TITLE
Default value is not respected for <Trans>

### ISSUE THREAD

**Issue by ramiel** [i18next/i18next-parser#206] opened 2020-02-10 12:09 UTC
- Is this a bug or a feature request?
Bug
- What version are you running (`0.x` or `1.x`)? 
1.0.2
- Which runner (cli, gulp...)?
cli
## What I'm trying to do?

Trying to extract key from 
`<Trans>A text</Trans>`

## How am I doing it?

`i18next --config i18next-parser.config.js`

Here is my config file:

```
{
  contextSeparator: '_',
  createOldCatalogs: false,
  defaultNamespace: 'translation',
  defaultValue: ''
  keepRemoved: false,
  keySeparator: false,
  lexers: {
    hbs: ['HandlebarsLexer'],
    handlebars: ['HandlebarsLexer'],

    htm: ['HTMLLexer'],
    html: ['HTMLLexer'],

    mjs: ['JavascriptLexer'],
    js: ['JavascriptLexer'], // if you're writing jsx inside .js files, change this to JsxLexer
    ts: ['JavascriptLexer'],
    jsx: ['JsxLexer'],
    tsx: ['JsxLexer'],

    default: ['JavascriptLexer'],
  },

  lineEnding: 'auto',
  locales: ['en', 'it'],

  namespaceSeparator: '::',
  output: 'public/locales/$LOCALE/$NAMESPACE.json',
  input: [`src/**/*.{ts,tsx}`],
  reactNamespace: true,
  sort: true,
  useKeysAsDefaultValue: false,
  verbose: false,
}
```

The command I'm running:

```
i18next --config i18next-parser.config.js
```

## What was the result?

```
{
  "A text": "A text"
}
```

## What was I expecting?

```
{
  "A text": ""
}
```

**Comment by karellm** [comment] 2020-02-10 22:01
Without seeing the parsed file, not much I can do. Please create a failing test case.

**Comment by ramiel** [comment] 2020-02-11 09:16
You can find a complete example at https://github.com/ramiel/parser-test

Look at the generated locale files: the key is also the value but it should not be

**Comment by ramiel** [comment] 2020-02-11 09:19
For comparison I added also the case with the `t` function that behaves correctly, producing only the key and not the value

**Comment by karellm** [comment] 2020-02-11 15:00
I'm not using react so I'm not sure what the behaviour should be. If you check the tests, that's seems to be on purpose: https://github.com/i18next/i18next-parser/blob/master/test/lexers/jsx-lexer.test.js#L27

@vincaslt Can you advise on this?

**Comment by ramiel** [comment] 2020-02-11 15:03
To me it seems the tests starting from [line 54](https://github.com/i18next/i18next-parser/blob/master/test/lexers/jsx-lexer.test.js#L54) are wrong. They says to test the key but they also do some assumption on the value, which is wrong

**Comment by vincaslt** [comment] 2020-02-11 20:34
Yeah, I think the test might not be entirely correct, as @ramiel said. It assumes that defaultValue is always key. There should be two separate tests, one with the flag that sets the default value as key, and the other without.

**Comment by vincaslt** [comment] 2020-02-22 00:07
Frankly, not sure why having a default value is not expected in your case. That's exactly the output I get from react-i18next:

```
// saveMissing: true

<Trans>test</Trans>
```

gives me `test: "test"`

**Comment by danielduan** [comment] 2020-03-11 22:11
Picking up on this:

```<Trans key="123" defaultValue="hello world" />```
gets extracted as
```123: ""```

Is this the expected behavior?

**Comment by vincaslt** [comment] 2020-08-07 22:49
Seems related to: #231 

According to https://react.i18next.com/latest/trans-component:
`defaults` is supposed to override children, currently parser doesn't handle it at all, and children field is empty.

**Comment by karellm** [comment] 2020-08-17 13:46
This should be fixed in `3.1.0`.

**Closed by karellm** 2020-08-17 13:46 UTC

**Comment by eszthoff** [comment] 2021-11-26 13:21
I have the same issue using the latest version of the parser. It extracts the value of Trans components and adds it in every language. Is there some setting I can change to have the default value for those keys?

**Comment by karellm** [comment] 2021-11-26 18:00
@eszthoff You are welcome to open a PR with a failing test case.

**Comment by eszthoff** [comment] 2021-11-29 12:04
@karellm  There is a repo attached with it. If that format isn't useful, can you point me to some docs on how you would like the problem demonstrated?

**Comment by karellm** [comment] 2021-11-30 11:53
I just have very limited bandwidth at the moment. I don't have the time to parse the repo to find differences. If you open a PR with a fix, it's a lot easier for me to review and merge it.

**Comment by eszthoff** [comment] 2021-11-30 12:03
I'm sorry, but I'm not familiar with your code base at all, and have a full time job myself. 
The problem that the original ticket describes is still there, I cannot see any changes in version 3 as mentioned above. 

In brief, content of `<Trans>` component is extracted from the code using the dev language, and puts in it all other language files (in English in my case). I'd expect empty value as for simple `t` functions.

For example:
`<Trans i18key="text">A text</Trans>`

is extracted in French etc as 
`"{"text": "A text"}`

while I would expect to see:
`"{"text": ""}`
