### ISSUE TITLE
Failing unit tests for object spread operator in v 1.0.0-beta26

### ISSUE THREAD

**Issue by phatgolo** [i18next/i18next-parser#122] opened 2018-09-03 14:58 UTC
- Is this a bug or a feature request?
Bug
- What version are you running (`0.x` or `1.x`)? 
1.0.0-beta26
- Which runner (cli, gulp...)?
cli

## What I'm trying to do?
Parse object spread operator

## How am I doing it?
By running your unit tests :)

The command I'm running:
```
npm test
```

## What was the result?
1) JavascriptLexer
       supports the spread operator in objects plugin:
     TypeError: Cannot read property 'type' of undefined
      at Object.base.Pattern (node_modules/acorn/dist/walk.js:301:12)
      at c (node_modules/acorn/dist/walk.js:29:15)
      at Object.base.ObjectPattern (node_modules/acorn/dist/walk.js:323:5)
      at c (node_modules/acorn/dist/walk.js:29:15)
      at Object.base.Pattern (node_modules/acorn/dist/walk.js:306:7)
      at c (node_modules/acorn/dist/walk.js:29:15)
      at Object.base.VariableDeclarator (node_modules/acorn/dist/walk.js:281:3)
      at c (node_modules/acorn/dist/walk.js:29:15)
      at Object.base.VariableDeclaration (node_modules/acorn/dist/walk.js:277:5)
      at c (node_modules/acorn/dist/walk.js:29:15)
      at Object.skipThrough (node_modules/acorn/dist/walk.js:183:37)
      at c (node_modules/acorn/dist/walk.js:29:15)
      at Object.base.Program.base.BlockStatement (node_modules/acorn/dist/walk.js:195:5)
      at c (node_modules/acorn/dist/walk.js:29:15)
      at Object.simple (node_modules/acorn/dist/walk.js:31:5)
      at JavascriptLexer.extract (src/lexers/javascript-lexer.js:47:10)
      at Context.<anonymous> (test/lexers/javascript-lexer.test.js:107:28)

## What was I expecting?
✓ supports the spread operator in objects plugin

## Aditional information
Please correct me if I'm wrong about this, but it seems like you have removed the "acorn-object-rest-spread" dependency, which leads to this error. It was there in version 1.0.0-beta22.

By re-adding this acorn-plugin to the javascript lexer, the test passes again.

**Comment by karellm** [comment] 2018-09-04 01:04
I can't reproduce this. Please run the following and let me know what you get:

```
rm -rf node_modules
git pull
npm install
npm test
```

**Comment by phatgolo** [comment] 2018-09-04 06:46
Removing the node_modules didn't help. I cloned this repo yesterday so pulling the latest version didn't help either. I've tried updating node to both latest stable and most recent version as well but without any luck.

Im on the latest commit on the ```master``` branch: ```a9c4442a204b2fb319e0d4b4c3a5571fda154c6a```.

**Comment by herrlax** [comment] 2018-09-04 13:58
I have the same issue as @phatgolo

**Comment by karellm** [comment] 2018-09-04 14:02
That's weird, I just a clean clone and it works. The test also pass on the CI. I'm on `Node 8.11.4`. What are your node versions?

**Comment by karellm** [comment] 2018-09-04 14:06
Ok so I was using `yarn` not `npm`. If I run the tests with `npm`, I can reproduce the bug. Is it an option for you to use `yarn` for the time being? I have little time today to investigate this.

**Comment by phatgolo** [comment] 2018-09-04 14:12
We have installed an older version to mitigate this issue (1.0.0-beta22) which still contains the ```acorn-object-rest-spread``` plugin so we have a workaround in place.

Thanks!

**Comment by phatgolo** [comment] 2018-09-04 14:53
I've made a PR for this

**Comment by karellm** [comment] 2018-09-04 15:03
Thanks for the PR, I'll test it shortly. I think the `package.lock` (used by yarn but not npm) is at fault. The library is still listed in it when it shouldn't.

**Comment by karellm** [comment] 2018-09-04 16:04
This should be fixed in `1.0.0-beta27`.

**Closed** 2019-02-17 23:17 UTC
Labels: bug
