### ISSUE TITLE
Fail on update does not work with multiple namespaces

### ISSUE THREAD

**Issue by AnotherHermit** [i18next/i18next-parser#489] opened 2021-12-09 16:14 UTC
## 🐛 Bug Report

When using multiple namespaces along with the "--fail-on-update" flag the result is always flagged as updated.
The issue seems to be the `countWithPlurals` that is used to check how many keys were added to a specific namespace. Since the `countWithPlurals` is set for the whole locale, not the specific namespace, the `addCount` for the namespace is wrong.
This can also be seen when the `verbose` setting is enabled, then the added keys will list the total number of keys for the locale minus the keys added in the specific namespace.

## To Reproduce

1. Use a setup with multiple namespaces with different keys in the different namespaces
2. Extract the keys once
3. Enable --fail-on-update (and verbose to see that the added keys is not 0)
4. Output will be flagged as having updates, even though output is the same

## Expected behavior

Fail on update should not always fail when run in environments with multiple namespaces

## Your Environment

- *runtime version*: node 16.5.0
- *i18next version*: 21.5.4
- *i18next-parser version*: 5.3.0
- *os*: Linux (WSL)

**Comment by riccardo-forina** [comment] 2021-12-14 18:26
I'm hitting this too.

**Comment by karellm** [comment] 2021-12-18 04:39
I'll happily review a PR if you want to take a spin at fixing this.

**Comment by karellm** [comment] 2022-04-03 16:52
This is likely fixed in `6.2.0`. Please not that `unique count` now includes plurals since it makes more sense with the new plural form.

**Closed by karellm** 2022-04-03 16:52 UTC

**Comment by alk-mandrianarijaona** [comment] 2022-04-04 07:41
@karellm unfortunately upgrading to 6.2.0 does not solve my issue yet but I was not able to reproduce it in a new project with the same config as my private project. I will reopen later if I can find a way to reproduce it. Thanks 🙏🏼
